### ISSUE TITLE
Trigger on family to select color

### ISSUE THREAD

**Issue by jennyknuth** [danielvartan/html-colors#1]
This package looks great, and thanks for the acknowledgement!

One way I would like to use this would be to be able to select from a color family. So if I trigger on `:blue` I could select from all the HTML colors in the blue family. I don't usually know which HTML color I want to use, but I usually do know if I want a blue or a brown or a gray or a pink, etc. From that key word, I'd love to see my standard options. 

Thank you! Nice product!

**Comment by danielvartan** [comment]
Hi Jenny,

I'm really glad you liked it! 😊

I believe a similar feature is already available in [Espanso](https://espanso.org/). It includes a pop-up window or search bar that allows you to search for triggers by keyword (like `blue`). You can also [configure](https://espanso.org/docs/configuration/options/#customizing-the-search-bar) it to appear whenever the system detects a trigger.

![image](https://github.com/user-attachments/assets/b4e31d61-8033-4c5f-b992-04e0063fd750)
